//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiCuoiKy
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG
    {
        public int MaBlog { get; set; }
        public string BlogTitle { get; set; }
        public string ContentTitle1 { get; set; }
        public string ContentTitle2 { get; set; }
        public string ContentTitle3 { get; set; }
        public string ContentTitle4 { get; set; }
        public string ContentTitle5 { get; set; }
        public string content1 { get; set; }
        public string content2 { get; set; }
        public string content3 { get; set; }
        public string content4 { get; set; }
        public string content5 { get; set; }
        public string content6 { get; set; }
        public string content7 { get; set; }
        public string content8 { get; set; }
        public string content9 { get; set; }
        public string content10 { get; set; }
        public Nullable<System.DateTime> BlogDate { get; set; }
        public string Author { get; set; }
        public string ImageContent1 { get; set; }
        public string ImageContent2 { get; set; }
        public string ImageContent3 { get; set; }
        public string ImageContent4 { get; set; }
        public string ImageContent5 { get; set; }
        public Nullable<bool> IsPopular { get; set; }
    }
}
