//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiCuoiKy
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONTHANGs = new HashSet<CHITIETDONTHANG>();
            this.GioHangs = new HashSet<GioHang>();
            this.YEUTHICHes = new HashSet<YEUTHICH>();
        }
    
        
        public int MaSanPham { get; set; }

        [DisplayName("Tên sản phẩm")]
        [Required(ErrorMessage ="Không được bỏ trống")]
        public string TenSanPham { get; set; }

        [DisplayName("Giá bán")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        [RegularExpression(@"[0-9]\d*(\.\d+)?$", ErrorMessage = "Bạn phải nhập số")]
        public decimal GiaBan { get; set; }

        [AllowHtml]
        [UIHint("tinymce_full")]
        public string MoTa { get; set; }

        [Display(Name ="Màn hình")]
        [Required(ErrorMessage ="Không được bỏ trống")]
        public string ManHinh { get; set; }

        [DisplayName("Hệ điều hành")]
        public string HeDieuHanh { get; set; }

        [DisplayName("Camera sau")]
        public string CameraSau { get; set; }

        [DisplayName("Camera trước")]
        public string CameraTruoc { get; set; }

        [DisplayName("CPU")]
        public string CPU { get; set; }

        [DisplayName("RAM")]
        public string RAM { get; set; }

        [DisplayName("Bộ nhớ trong")]
        public string BoNhoTrong { get; set; }

        [DisplayName("SIM")]
        public string SIM { get; set; }

        [DisplayName("Pin")]
        public string Pin { get; set; }

        [DisplayName("Ảnh 1")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string AnhBia { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }

        [DisplayName("Số lượng")]
        public Nullable<int> SoLuongTon { get; set; }

        [DisplayName("Loại sản phẩm")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public Nullable<int> MaLSP { get; set; }

        [DisplayName("Nhà cung cấp")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public Nullable<int> MaNCC { get; set; }
        public Nullable<bool> DaXoa { get; set; }

        [DisplayName("Ảnh 2")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string AnhBia1 { get; set; }

        [DisplayName("Khuyến mãi (%)")]
        [RegularExpression(@"[0-9]\d*(\.\d+)?$", ErrorMessage ="Bạn phải nhập số")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public Nullable<decimal> KhuyenMai { get; set; }
        public Nullable<bool> GiaSoc { get; set; }
        public Nullable<int> Sao { get; set; }
        public string Mau1 { get; set; }
        public string Mau2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONTHANG> CHITIETDONTHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUTHICH> YEUTHICHes { get; set; }
    }
}
